In [1]:
import tensorflow as tf

In [3]:
# log_device_placement=True, 可以打印使用的设备信息
# allow_soft_placement=True, 当指定的设备不可用时，允许tf选择现有和受支持的设备
config=tf.ConfigProto(log_device_placement=True, allow_soft_placement=True)

with tf.device("/cpu:0"):
    rand_t=tf.random_uniform([50,50],0,10,dtype=tf.float32, seed=0)
    a=tf.Variable(rand_t)
    b=tf.Variable(rand_t)
    c=tf.matmul(a, b)
    init=tf.global_variables_initializer()
    
with tf.Session(config=config) as sess:
    sess.run(init)
    print(sess.run(c))

Device mapping:

[[1405.2432 1441.7412 1364.38   ... 1480.2251 1279.0063 1620.0938]
 [1232.6589 1344.4458 1169.7092 ... 1205.1285 1040.5566 1421.967 ]
 [1209.3167 1180.3208 1158.1396 ... 1200.0343 1014.0322 1222.5107]
 ...
 [1298.9648 1262.9236 1205.6917 ... 1396.4789 1090.7252 1437.2411]
 [1118.2473 1209.0151 1077.7229 ... 1180.7024 1076.4695 1139.742 ]
 [1200.8866 1297.2267 1260.0101 ... 1289.4297 1165.2446 1433.4183]]


In [4]:
# 选择多个设备
c=[]
for d in ["/cpu:0","/cpu:1"]:
    with tf.device(d):
        rand_t=tf.random_uniform([50,50],0,10,dtype=tf.float32, seed=0)
        a=tf.Variable(rand_t)
        b=tf.Variable(rand_t)
        c.append(tf.matmul(a, b))
        init=tf.global_variables_initializer()
        
with tf.Session(config=config) as sess:
    sess.run(init)
    print(sess.run(c))

Device mapping:

[array([[1405.2432, 1441.7412, 1364.38  , ..., 1480.2251, 1279.0063,
        1620.0938],
       [1232.6589, 1344.4458, 1169.7092, ..., 1205.1285, 1040.5566,
        1421.967 ],
       [1209.3167, 1180.3208, 1158.1396, ..., 1200.0343, 1014.0322,
        1222.5107],
       ...,
       [1298.9648, 1262.9236, 1205.6917, ..., 1396.4789, 1090.7252,
        1437.2411],
       [1118.2473, 1209.0151, 1077.7229, ..., 1180.7024, 1076.4695,
        1139.742 ],
       [1200.8866, 1297.2267, 1260.0101, ..., 1289.4297, 1165.2446,
        1433.4183]], dtype=float32), array([[1405.2432, 1441.7412, 1364.38  , ..., 1480.2251, 1279.0063,
        1620.0938],
       [1232.6589, 1344.4458, 1169.7092, ..., 1205.1285, 1040.5566,
        1421.967 ],
       [1209.3167, 1180.3208, 1158.1396, ..., 1200.0343, 1014.0322,
        1222.5107],
       ...,
       [1298.9648, 1262.9236, 1205.6917, ..., 1396.4789, 1090.7252,
        1437.2411],
       [1118.2473, 1209.0151, 1077.7229, ..., 1180.7024, 1076