In [2]:
import tensorflow as tf

In [3]:
sess=tf.InteractiveSession()

In [4]:
# 5x5 单位矩阵
I_matrix=tf.eye(5)
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# 矩阵变量，初始化为10x10单位矩阵
X=tf.Variable(tf.eye(10))
X.initializer.run()
print(X.eval())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:
# 矩阵相乘
A=tf.Variable(tf.random_normal([5,10],seed=0))
A.initializer.run()
product=tf.matmul(A, X)
print(product.eval())

[[-0.3991576   2.1044393   0.17107224  0.54651815 -2.4234028   0.422554
   0.28943786 -0.5043041  -0.96068907 -0.65109813]
 [ 0.11453361 -0.10354779 -1.300912   -0.5038757   0.02013604 -0.09342099
  -0.12571211 -0.04320283 -0.46242726  0.5460443 ]
 [-0.3929454   2.5214329  -1.4561468   0.903801   -0.26212615  0.6240329
  -0.2521848   0.7573418  -0.8864083   1.3231359 ]
 [-1.198264    0.7606799   0.84330815  0.2508936   0.2366665  -1.8962964
  -1.4281125  -0.53130555  0.2552794  -0.93993634]
 [-1.5221636  -0.00822365 -0.99627084  2.2360663  -1.2033943  -0.7806828
   0.06733078 -0.09443122 -0.79472643 -1.0500034 ]]


In [7]:
# tf.cast
b=tf.Variable(tf.random_uniform([5,10],0,2,seed=0,dtype=tf.int32))
b.initializer.run()
print(b.eval())
print('------------------------------')
b_new=tf.cast(b,dtype=tf.float32)
print(b_new.eval())



[[1 1 0 1 1 0 1 0 1 1]
 [1 0 1 0 1 0 1 1 1 0]
 [1 1 0 0 1 1 0 1 1 1]
 [1 0 0 0 1 0 1 1 0 1]
 [1 1 1 0 0 1 1 1 0 0]]
------------------------------
[[1. 1. 0. 1. 1. 0. 1. 0. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1. 1. 0.]
 [1. 1. 0. 0. 1. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 0.]]


In [8]:
# tf.add
t_sum=tf.add(product, b_new)
t_sub=product - b_new
print("A*X + b\n", t_sum.eval())
print("\n")
print("A*X - b\n", t_sub.eval())

A*X + b
 [[ 0.60084236  3.1044393   0.17107224  1.5465181  -1.4234028   0.422554
   1.2894379  -0.5043041   0.03931093  0.34890187]
 [ 1.1145337  -0.10354779 -0.30091202 -0.5038757   1.020136   -0.09342099
   0.8742879   0.9567972   0.53757274  0.5460443 ]
 [ 0.6070546   3.5214329  -1.4561468   0.903801    0.73787385  1.624033
  -0.2521848   1.7573419   0.11359167  2.3231359 ]
 [-0.198264    0.7606799   0.84330815  0.2508936   1.2366664  -1.8962964
  -0.4281125   0.46869445  0.2552794   0.06006366]
 [-0.5221636   0.99177635  0.00372916  2.2360663  -1.2033943   0.2193172
   1.0673308   0.9055688  -0.79472643 -1.0500034 ]]


A*X - b
 [[-1.3991576   1.1044393   0.17107224 -0.45348185 -3.4234028   0.422554
  -0.7105621  -0.5043041  -1.9606891  -1.6510981 ]
 [-0.8854664  -0.10354779 -2.300912   -0.5038757  -0.97986394 -0.09342099
  -1.1257122  -1.0432029  -1.4624273   0.5460443 ]
 [-1.3929454   1.5214329  -1.4561468   0.903801   -1.2621262  -0.3759671
  -0.2521848  -0.2426582  -1.8864083   

In [9]:
# 按元素相乘，乘以一个标量，按元素相除，按元素相除取余等
a=tf.Variable(tf.random_normal([4,5],mean=0,stddev=2,seed=0))
b=tf.Variable(tf.random_normal([4,5],mean=0,stddev=2,seed=1))

## Element-wise multiplication
A=a*b

## Multiplication with a scalar
B=tf.scalar_mul(2, A)

## Element-wise division
C=tf.math.truediv(a, b)

## Element-wise remainder of division
D=tf.mod(a, b)

init_op=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer=tf.summary.FileWriter('graphs',sess.graph)
    a,b,A_R,B_R,C_R,D_R = sess.run([a,b,A,B,C,D])
    print("a\n",a,"\nb\n",b,"a*b\n",A_R,"\n2*a*b\n",B_R,"\na/b\n",C_R,"\na%b\n",D_R)
    
writer.close()
    

a
 [[-0.7983152   4.2088785   0.3421445   1.0930363  -4.8468056 ]
 [ 0.845108    0.5788757  -1.0086082  -1.9213781  -1.3021963 ]
 [ 0.22906722 -0.20709558 -2.601824   -1.0077513   0.04027208]
 [-0.18684198 -0.25142422 -0.08640566 -0.9248545   1.0920886 ]] 
b
 [[-1.6226364   2.9691975   0.13065875 -4.8854084   0.1984968 ]
 [ 1.1824486   1.1856459  -4.245859   -1.4457945  -0.11254076]
 [ 1.2870896  -0.52864814  3.7132664   1.1356834  -0.7656718 ]
 [-2.9706867   2.5235422  -0.05061216 -0.5292594   3.0656276 ]] a*b
 [[ 1.29537535e+00  1.24969912e+01  4.47041690e-02 -5.33992863e+00
  -9.62075412e-01]
 [ 9.99296784e-01  6.86341643e-01  4.28240824e+00  2.77791786e+00
   1.46550149e-01]
 [ 2.94830024e-01  1.09480694e-01 -9.66126537e+00 -1.14448655e+00
  -3.08351945e-02]
 [ 5.55049002e-01 -6.34479642e-01  4.37317695e-03  4.89487946e-01
   3.34793687e+00]] 
2*a*b
 [[ 2.5907507e+00  2.4993982e+01  8.9408338e-02 -1.0679857e+01
  -1.9241508e+00]
 [ 1.9985936e+00  1.3726833e+00  8.5648165e+00  5.555

In [ ]:
tensorbo